version: '3.7'

services:
  sgp-db:
    container_name: postgres
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
      TZ: America/Manaus
    ports:
      - '5432:5432'
    restart: unless-stopped
